"""Electrical output of PVDF-based piezoelectric nanogenerators (PENGs).

The device is modelled as a charge source in parallel with its own
capacitance C_p = eps0 eps_r A / t (Norton equivalent below resonance).
"""

import numpy as np

from .constants import EPS0


def capacitance(eps_r, area, thickness):
    """Parallel-plate capacitance (F) of the film."""
    return EPS0 * eps_r * area / thickness


def charge_33(d33, force):
    """Charge (C) generated by a force applied along the poling axis, Q = d33 F."""
    return d33 * force


def charge_31(d31, stress_1, electrode_area):
    """Charge (C) from in-plane stress in bending / stretching mode, Q = d31 sigma_1 A."""
    return d31 * stress_1 * electrode_area


def open_circuit_voltage(charge, cap):
    """Open-circuit voltage V_oc = Q / C (V)."""
    return charge / cap


def open_circuit_voltage_33(d33, stress, thickness, eps_r):
    """Open-circuit voltage in compression, V_oc = g33 sigma t = d33 sigma t / (eps0 eps_r)."""
    return d33 * stress * thickness / (EPS0 * eps_r)


def stored_energy(charge, cap):
    """Electrostatic energy (J) available per loading half-cycle in open circuit, Q^2 / 2C."""
    return charge ** 2 / (2 * cap)


def load_power(charge_amplitude, cap, frequency, resistance):
    """Average power (W) into a resistive load under sinusoidal loading.

        P = (omega Q0)^2 R / (2 (1 + (omega R C)^2))
    """
    omega = 2 * np.pi * frequency
    r = np.asarray(resistance, dtype=float)
    return (omega * charge_amplitude) ** 2 * r / (2 * (1 + (omega * r * cap) ** 2))


def optimal_load(cap, frequency):
    """Matched load R_opt = 1 / (omega C) (ohm)."""
    return 1 / (2 * np.pi * frequency * cap)


def max_power(charge_amplitude, cap, frequency):
    """Power at the matched load, P_max = omega Q0^2 / (4 C) (W)."""
    omega = 2 * np.pi * frequency
    return omega * charge_amplitude ** 2 / (4 * cap)


def load_voltage_amplitude(charge_amplitude, cap, frequency, resistance):
    """Voltage amplitude (V) across the load, omega Q0 R / sqrt(1 + (omega R C)^2)."""
    omega = 2 * np.pi * frequency
    r = np.asarray(resistance, dtype=float)
    return omega * charge_amplitude * r / np.sqrt(1 + (omega * r * cap) ** 2)


def bridge_charging(charge_amplitude, cap_p, cap_s, n_half_cycles, diode_drop=0.0):
    """Storage-capacitor voltage after each half-cycle through a full-wave bridge.

    In each half-cycle the source displaces 2 Q0. Part of it, 2 C_p (V_s + 2 V_d),
    is spent reversing the piezo capacitor before the diodes conduct; the
    rest is shared between C_p and C_s:

        dV = (2 Q0 - 2 C_p (V_s + 2 V_d)) / (C_p + C_s)

    The voltage saturates at V_oc - 2 V_d with V_oc = Q0 / C_p.
    Returns an array of n_half_cycles + 1 voltages starting at 0.
    """
    v = np.zeros(n_half_cycles + 1)
    for k in range(n_half_cycles):
        dq = 2 * charge_amplitude - 2 * cap_p * (v[k] + 2 * diode_drop)
        v[k + 1] = v[k] + max(dq, 0.0) / (cap_p + cap_s)
    return v


def power_density(power, area=None, volume=None):
    """Power per area (W/m^2) or per volume (W/m^3); give exactly one of the two."""
    if (area is None) == (volume is None):
        raise ValueError("give exactly one of area or volume")
    return power / (area if area is not None else volume)
